# Generated by Django 2.0.6 on 2018-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20180629_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_pg',
            field=models.CharField(blank=True, choices=[('1', 'Completo'), ('2', 'Aprovado'), ('3', 'Em Análise'), ('4', 'Devolvido'), ('5', 'Cancelado')], max_length=10, null=True, verbose_name='Status PagSeguro'),
        ),
    ]
