# Generated by Django 2.0.6 on 2018-07-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180629_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='forwarded',
            field=models.BooleanField(default=False, verbose_name='Encaminhado'),
        ),
        migrations.AddField(
            model_name='order',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='Enviado'),
        ),
    ]
