# Generated by Django 2.0.6 on 2019-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20180712_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dinheiro R$'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=10, verbose_name='Status do Pedido'),
        ),
    ]
